### ISSUE TITLE
リファクタリング

### ISSUE THREAD

**Issue by nokazn** [nokazn/Otonabe#479]
## Todos 

- [x] prop名
  - `is-hoge` とかになってるやつ
- [x] ~~`$header` を `$fab` に rename する~~ $header 内を整理する
- [x] `$window` を `$screen` に rename する
- [x] `@include`
- [x] ディレクトリ構成
  - `~/client/plugin/local`
  - `~/plugin/spotify`
- [x] linter, `.editorconfig` 等見直す
